export const reusableResources = [
  {
    name: "BalBERT",
    type: "Language model",
    owner: "Shah Bakhsh",
    license: "Apache-2.0",
    url: "https://huggingface.co/shah-bakhsh/BalBERT",
    note: "Balochi-adapted XLM-R encoder for embeddings and downstream NLP.",
  },
  {
    name: "Balochi Tokenizer",
    type: "Tokenizer",
    owner: "Shah Bakhsh",
    license: "Apache-2.0",
    url: "https://huggingface.co/shah-bakhsh/balochi-tokenizer",
    note: "Research-grade BPE tokenizer trained on a normalized Balochi corpus.",
  },
  {
    name: "BalPOS",
    type: "POS tagging",
    owner: "Shah Bakhsh",
    license: "Apache-2.0",
    url: "https://huggingface.co/shah-bakhsh/BalPOS",
    note: "Universal part-of-speech tagger fine-tuned from BalBERT.",
  },
  {
    name: "Balochi STT",
    type: "Speech-to-text",
    owner: "Aynkader",
    license: "Review model card",
    url: "https://huggingface.co/Aynkader/Balochi_STT",
    note: "Whisper-small fine-tune producing Latin-script Balochi.",
  },
  {
    name: "Balochi TTS — Three Speakers",
    type: "Text-to-speech",
    owner: "Aynkader",
    license: "Apache-2.0",
    url: "https://huggingface.co/Aynkader/Balochi-TTS-Three-Speakers",
    note: "SpeechT5 Balochi voice baseline with three speaker embeddings.",
  },
  {
    name: "Balochi Latin Parallel Corpus",
    type: "Translation dataset",
    owner: "Aynkader",
    license: "License audit required",
    url: "https://huggingface.co/datasets/Aynkader/Balochi-dataset",
    note: "33,216 English–Balochi Latin sentence pairs. Useful for translation research, but a standard reuse license should be confirmed before importing into Zubán.",
  },
  {
    name: "Balochi Translation Model",
    type: "Machine translation",
    owner: "Bakhteyar",
    license: "MIT",
    url: "https://huggingface.co/Bakhteyar/Balochi-Model",
    note: "Marian-style English-to-Balochi Latin model. The model is open, but its training data and evaluation documentation need independent audit before production use.",
  },
  {
    name: "Balochi Wordlists",
    type: "Lexical data",
    owner: "Junaid Qadir et al.",
    license: "Attribution requested",
    url: "https://github.com/JunaidQadirB/Balochi-Wordlists",
    note: "Community wordlists in Sayad and UniBal scripts; license terms need audit before import.",
  },
] as const;
